name: release-docker-develop

on:
  push:
    branches:
      - main

concurrency: release-docker-develop

env:
  FORCE_COLOR: 1
  DO_NOT_TRACK: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Get git commit
        id: git-commit
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> "$GITHUB_OUTPUT"

      - name: Lowercase repository name
        id: repository-lowercase
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - uses: ./.github/actions/docker-publish
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/${{ steps.repository-lowercase.outputs.repository }}:${{ steps.git-commit.outputs.SHORT_SHA }}
            ghcr.io/${{ steps.repository-lowercase.outputs.repository }}:develop
          build-args: |
            VERSION=${{ steps.git-commit.outputs.SHORT_SHA }}
          dockerUser: ${{ secrets.DOCKER_USER }}
          dockerPassword: ${{ secrets.DOCKER_PAT }}
