name: release-docker-develop

on:
  push:
    branches:
      - main

concurrency: release-docker-develop

env:
  FORCE_COLOR: 1
  DO_NOT_TRACK: 1

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.git-commit.outputs.SHORT_SHA }}
    steps:
      - name: Get git commit
        id: git-commit
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_docker-publish-multiarch.yml
    with:
      version_tag: ${{ needs.prepare.outputs.short_sha }}
      additional_tags: '["develop"]'
    secrets: inherit
