name: release-docker-latest

on:
  push:
    tags:
      - '*'

concurrency: release-docker-latest

env:
  FORCE_COLOR: 1
  DO_NOT_TRACK: 1

jobs:
  build:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/_docker-publish-multiarch.yml
    with:
      version_tag: ${{ github.ref_name }}
      additional_tags: '["latest"]'
    secrets: inherit
